package com.example.english_app.entity.enums;

public enum LearningEventType {
    PLACEMENT_COMPLETED,
    VOCAB_REVIEWED,
    VOCAB_ROUND_COMPLETED,
    PRONUNCIATION_PRACTICED,
    SPEAKING_SESSION_EVALUATED,
    ASSIGNMENT_GRADED,
    ROADMAP_GENERATED,
    ROADMAP_MODULE_COMPLETED,
    ROADMAP_WEEK_COMPLETED,
    ROADMAP_COMPLETED
}

