INSERT INTO questions (cefr_level, skill, question_type, content_json, correct_answer, timeout_seconds, is_active, created_at) VALUES
-- A1 (20 questions)
('A1', 'VOCABULARY', 'MULTIPLE_CHOICE', '{"question": "I need to buy some ___ at the bakery.", "options": ["meat", "bread", "milk", "vegetables"]}'::jsonb, 'bread', 30, true, CURRENT_TIMESTAMP),
('A1', 'VOCABULARY', 'MULTIPLE_CHOICE', '{"question": "I drink a glass of ___ every morning.", "options": ["bread", "water", "apple", "cheese"]}'::jsonb, 'water', 30, true, CURRENT_TIMESTAMP),
('A1', 'VOCABULARY', 'MULTIPLE_CHOICE', '{"question": "My father''s sister is my ___.", "options": ["aunt", "uncle", "cousin", "grandmother"]}'::jsonb, 'aunt', 30, true, CURRENT_TIMESTAMP),
('A1', 'VOCABULARY', 'MULTIPLE_CHOICE', '{"question": "We use a ___ to cut food.", "options": ["spoon", "fork", "knife", "plate"]}'::jsonb, 'knife', 30, true, CURRENT_TIMESTAMP),
('A1', 'VOCABULARY', 'MULTIPLE_CHOICE', '{"question": "I have two ___ on my face.", "options": ["noses", "ears", "eyes", "mouths"]}'::jsonb, 'eyes', 30, true, CURRENT_TIMESTAMP),
('A1', 'GRAMMAR', 'MULTIPLE_CHOICE', '{"question": "She ___ to school every day.", "options": ["go", "goes", "going", "to go"]}'::jsonb, 'goes', 30, true, CURRENT_TIMESTAMP),
('A1', 'GRAMMAR', 'MULTIPLE_CHOICE', '{"question": "___ you like apples?", "options": ["Do", "Does", "Are", "Is"]}'::jsonb, 'Do', 30, true, CURRENT_TIMESTAMP),
('A1', 'GRAMMAR', 'MULTIPLE_CHOICE', '{"question": "He ___ a new car.", "options": ["have", "has", "having", "is"]}'::jsonb, 'has', 30, true, CURRENT_TIMESTAMP),
('A1', 'GRAMMAR', 'FILL_BLANK', '{"question": "___ is your name?"}'::jsonb, 'What', 30, true, CURRENT_TIMESTAMP),
('A1', 'GRAMMAR', 'FILL_BLANK', '{"question": "I ___ a student."}'::jsonb, 'am', 30, true, CURRENT_TIMESTAMP),
('A1', 'READING', 'READING_COMPREHENSION', '{"text": "My dog is small and brown. He likes to play with a ball.", "question": "What color is the dog?", "options": ["Black", "White", "Brown", "Yellow"]}'::jsonb, 'Brown', 90, true, CURRENT_TIMESTAMP),
('A1', 'READING', 'READING_COMPREHENSION', '{"text": "Mary has a red pen and a blue notebook. She likes to write.", "question": "What color is her notebook?", "options": ["Red", "Blue", "Green", "Yellow"]}'::jsonb, 'Blue', 90, true, CURRENT_TIMESTAMP),
('A1', 'READING', 'READING_COMPREHENSION', '{"text": "I wake up at 7 AM. Then I eat breakfast.", "question": "What time do I wake up?", "options": ["6 AM", "7 AM", "8 AM", "9 AM"]}'::jsonb, '7 AM', 90, true, CURRENT_TIMESTAMP),
('A1', 'READING', 'READING_COMPREHENSION', '{"text": "My favorite sport is soccer. I play it with my friends.", "question": "What is my favorite sport?", "options": ["Tennis", "Basketball", "Soccer", "Golf"]}'::jsonb, 'Soccer', 90, true, CURRENT_TIMESTAMP),
('A1', 'READING', 'READING_COMPREHENSION', '{"text": "Today is Monday. Tomorrow is Tuesday.", "question": "What day is tomorrow?", "options": ["Sunday", "Monday", "Tuesday", "Wednesday"]}'::jsonb, 'Tuesday', 90, true, CURRENT_TIMESTAMP),
('A1', 'PRONUNCIATION', 'PRONUNCIATION', '{"word": "hello", "ipa": "/həˈloʊ/"}'::jsonb, 'hello', 10, true, CURRENT_TIMESTAMP),
('A1', 'PRONUNCIATION', 'PRONUNCIATION', '{"word": "good", "ipa": "/ɡʊd/"}'::jsonb, 'good', 10, true, CURRENT_TIMESTAMP),
('A1', 'PRONUNCIATION', 'PRONUNCIATION', '{"word": "house", "ipa": "/haʊs/"}'::jsonb, 'house', 10, true, CURRENT_TIMESTAMP),
('A1', 'PRONUNCIATION', 'PRONUNCIATION', '{"word": "name", "ipa": "/neɪm/"}'::jsonb, 'name', 10, true, CURRENT_TIMESTAMP),
('A1', 'PRONUNCIATION', 'PRONUNCIATION', '{"word": "friend", "ipa": "/frend/"}'::jsonb, 'friend', 10, true, CURRENT_TIMESTAMP),

-- A2 (20 questions)
('A2', 'VOCABULARY', 'MULTIPLE_CHOICE', '{"question": "Please ___ the door when you leave.", "options": ["open", "close", "break", "paint"]}'::jsonb, 'close', 30, true, CURRENT_TIMESTAMP),
('A2', 'VOCABULARY', 'MULTIPLE_CHOICE', '{"question": "I need to buy some ___ to send a letter.", "options": ["stamps", "coins", "cards", "paper"]}'::jsonb, 'stamps', 30, true, CURRENT_TIMESTAMP),
('A2', 'VOCABULARY', 'MULTIPLE_CHOICE', '{"question": "We went to the ___ to watch a movie.", "options": ["hospital", "cinema", "park", "museum"]}'::jsonb, 'cinema', 30, true, CURRENT_TIMESTAMP),
('A2', 'VOCABULARY', 'MULTIPLE_CHOICE', '{"question": "I always wear a ___ when it is cold.", "options": ["t-shirt", "coat", "skirt", "shorts"]}'::jsonb, 'coat', 30, true, CURRENT_TIMESTAMP),
('A2', 'VOCABULARY', 'MULTIPLE_CHOICE', '{"question": "Can I have the ___, please? I want to pay.", "options": ["menu", "bill", "plate", "food"]}'::jsonb, 'bill', 30, true, CURRENT_TIMESTAMP),
('A2', 'GRAMMAR', 'MULTIPLE_CHOICE', '{"question": "They have been living here ___ 2015.", "options": ["for", "in", "since", "at"]}'::jsonb, 'since', 30, true, CURRENT_TIMESTAMP),
('A2', 'GRAMMAR', 'MULTIPLE_CHOICE', '{"question": "I ___ a good book yesterday.", "options": ["read", "readed", "reading", "reads"]}'::jsonb, 'read', 30, true, CURRENT_TIMESTAMP),
('A2', 'GRAMMAR', 'MULTIPLE_CHOICE', '{"question": "This car is ___ than that one.", "options": ["fast", "faster", "fastest", "more fast"]}'::jsonb, 'faster', 30, true, CURRENT_TIMESTAMP),
('A2', 'GRAMMAR', 'FILL_BLANK', '{"question": "I am looking ___ my keys. Have you seen them?"}'::jsonb, 'for', 30, true, CURRENT_TIMESTAMP),
('A2', 'GRAMMAR', 'FILL_BLANK', '{"question": "She is interested ___ learning English."}'::jsonb, 'in', 30, true, CURRENT_TIMESTAMP),
('A2', 'READING', 'READING_COMPREHENSION', '{"text": "Tomorrow, we will visit the museum. It opens at 10 AM. We should arrive early.", "question": "When does the museum open?", "options": ["8 AM", "9 AM", "10 AM", "11 AM"]}'::jsonb, '10 AM', 90, true, CURRENT_TIMESTAMP),
('A2', 'READING', 'READING_COMPREHENSION', '{"text": "I went to Paris last summer. I saw the Eiffel Tower and ate a lot of croissants.", "question": "Where did I go last summer?", "options": ["London", "Rome", "Paris", "Berlin"]}'::jsonb, 'Paris', 90, true, CURRENT_TIMESTAMP),
('A2', 'READING', 'READING_COMPREHENSION', '{"text": "John is a doctor. He works at the city hospital from 9 AM to 5 PM.", "question": "What is John''s job?", "options": ["Teacher", "Doctor", "Engineer", "Driver"]}'::jsonb, 'Doctor', 90, true, CURRENT_TIMESTAMP),
('A2', 'READING', 'READING_COMPREHENSION', '{"text": "Cats are independent animals. Dogs usually need more attention from their owners.", "question": "Which animal needs more attention?", "options": ["Cats", "Dogs", "Birds", "Fish"]}'::jsonb, 'Dogs', 90, true, CURRENT_TIMESTAMP),
('A2', 'READING', 'READING_COMPREHENSION', '{"text": "The weather today is rainy. We cannot go to the park.", "question": "Why can''t they go to the park?", "options": ["It is sunny", "It is snowy", "It is rainy", "It is windy"]}'::jsonb, 'It is rainy', 90, true, CURRENT_TIMESTAMP),
('A2', 'PRONUNCIATION', 'PRONUNCIATION', '{"word": "island", "ipa": "/ˈaɪlənd/"}'::jsonb, 'island', 10, true, CURRENT_TIMESTAMP),
('A2', 'PRONUNCIATION', 'PRONUNCIATION', '{"word": "castle", "ipa": "/ˈkæsl/"}'::jsonb, 'castle', 10, true, CURRENT_TIMESTAMP),
('A2', 'PRONUNCIATION', 'PRONUNCIATION', '{"word": "listen", "ipa": "/ˈlɪsn/"}'::jsonb, 'listen', 10, true, CURRENT_TIMESTAMP),
('A2', 'PRONUNCIATION', 'PRONUNCIATION', '{"word": "water", "ipa": "/ˈwɔːtər/"}'::jsonb, 'water', 10, true, CURRENT_TIMESTAMP),
('A2', 'PRONUNCIATION', 'PRONUNCIATION', '{"word": "often", "ipa": "/ˈɔːfn/"}'::jsonb, 'often', 10, true, CURRENT_TIMESTAMP),

-- B1 (20 questions)
('B1', 'VOCABULARY', 'MULTIPLE_CHOICE', '{"question": "Can you ___ the volume? It''s too loud.", "options": ["turn up", "turn on", "turn off", "turn down"]}'::jsonb, 'turn down', 30, true, CURRENT_TIMESTAMP),
('B1', 'VOCABULARY', 'MULTIPLE_CHOICE', '{"question": "He decided to ___ his job because he was unhappy.", "options": ["quit", "fire", "hire", "apply"]}'::jsonb, 'quit', 30, true, CURRENT_TIMESTAMP),
('B1', 'VOCABULARY', 'MULTIPLE_CHOICE', '{"question": "You should always ___ your seatbelt when driving.", "options": ["fasten", "tie", "lock", "hold"]}'::jsonb, 'fasten', 30, true, CURRENT_TIMESTAMP),
('B1', 'VOCABULARY', 'MULTIPLE_CHOICE', '{"question": "The ___ was delayed due to bad weather.", "options": ["flight", "flying", "fly", "flown"]}'::jsonb, 'flight', 30, true, CURRENT_TIMESTAMP),
('B1', 'VOCABULARY', 'MULTIPLE_CHOICE', '{"question": "We need to ___ a solution to this problem.", "options": ["make", "do", "find", "take"]}'::jsonb, 'find', 30, true, CURRENT_TIMESTAMP),
('B1', 'GRAMMAR', 'MULTIPLE_CHOICE', '{"question": "I wish I ___ more time to finish the project.", "options": ["have", "has", "had", "will have"]}'::jsonb, 'had', 30, true, CURRENT_TIMESTAMP),
('B1', 'GRAMMAR', 'MULTIPLE_CHOICE', '{"question": "She ___ TV when the phone rang.", "options": ["watches", "was watching", "is watching", "watched"]}'::jsonb, 'was watching', 30, true, CURRENT_TIMESTAMP),
('B1', 'GRAMMAR', 'MULTIPLE_CHOICE', '{"question": "If it rains, we ___ at home.", "options": ["stay", "will stay", "stayed", "would stay"]}'::jsonb, 'will stay', 30, true, CURRENT_TIMESTAMP),
('B1', 'GRAMMAR', 'FILL_BLANK', '{"question": "She is responsible ___ organizing the event."}'::jsonb, 'for', 30, true, CURRENT_TIMESTAMP),
('B1', 'GRAMMAR', 'FILL_BLANK', '{"question": "He has been working here ___ three years."}'::jsonb, 'for', 30, true, CURRENT_TIMESTAMP),
('B1', 'READING', 'READING_COMPREHENSION', '{"text": "Despite the heavy rain, the football match continued. The players were exhausted but determined.", "question": "Why did the match continue?", "options": ["Because the weather was fine", "Despite the weather", "It was a final match", "The players were tired"]}'::jsonb, 'Despite the weather', 90, true, CURRENT_TIMESTAMP),
('B1', 'READING', 'READING_COMPREHENSION', '{"text": "The new restaurant in town serves amazing Italian food. However, it is quite expensive.", "question": "What is the downside of the restaurant?", "options": ["The food is bad", "It is expensive", "It is far away", "It is small"]}'::jsonb, 'It is expensive', 90, true, CURRENT_TIMESTAMP),
('B1', 'READING', 'READING_COMPREHENSION', '{"text": "I used to play the piano when I was younger, but I haven''t played in years.", "question": "Does the person play the piano now?", "options": ["Yes, every day", "No, not anymore", "Yes, sometimes", "Only on weekends"]}'::jsonb, 'No, not anymore', 90, true, CURRENT_TIMESTAMP),
('B1', 'READING', 'READING_COMPREHENSION', '{"text": "Traffic was terrible this morning because of an accident on the highway.", "question": "Why was traffic terrible?", "options": ["Rain", "Snow", "An accident", "Road construction"]}'::jsonb, 'An accident', 90, true, CURRENT_TIMESTAMP),
('B1', 'READING', 'READING_COMPREHENSION', '{"text": "Please reply to this email by Friday if you want to attend the meeting.", "question": "When is the deadline to reply?", "options": ["Monday", "Wednesday", "Friday", "Sunday"]}'::jsonb, 'Friday', 90, true, CURRENT_TIMESTAMP),
('B1', 'PRONUNCIATION', 'PRONUNCIATION', '{"word": "comfortable", "ipa": "/ˈkʌmftərbəl/"}'::jsonb, 'comfortable', 10, true, CURRENT_TIMESTAMP),
('B1', 'PRONUNCIATION', 'PRONUNCIATION', '{"word": "vegetable", "ipa": "/ˈvedʒtəbəl/"}'::jsonb, 'vegetable', 10, true, CURRENT_TIMESTAMP),
('B1', 'PRONUNCIATION', 'PRONUNCIATION', '{"word": "recipe", "ipa": "/ˈresəpi/"}'::jsonb, 'recipe', 10, true, CURRENT_TIMESTAMP),
('B1', 'PRONUNCIATION', 'PRONUNCIATION', '{"word": "knowledge", "ipa": "/ˈnɑːlɪdʒ/"}'::jsonb, 'knowledge', 10, true, CURRENT_TIMESTAMP),
('B1', 'PRONUNCIATION', 'PRONUNCIATION', '{"word": "doubt", "ipa": "/daʊt/"}'::jsonb, 'doubt', 10, true, CURRENT_TIMESTAMP),

-- B2 (20 questions)
('B2', 'VOCABULARY', 'MULTIPLE_CHOICE', '{"question": "The new evidence completely ___ his theory.", "options": ["supports", "contradicts", "proves", "explains"]}'::jsonb, 'contradicts', 30, true, CURRENT_TIMESTAMP),
('B2', 'VOCABULARY', 'MULTIPLE_CHOICE', '{"question": "She has a very ___ schedule this week with back-to-back meetings.", "options": ["loose", "hectic", "calm", "slow"]}'::jsonb, 'hectic', 30, true, CURRENT_TIMESTAMP),
('B2', 'VOCABULARY', 'MULTIPLE_CHOICE', '{"question": "The government is trying to ___ the crisis.", "options": ["mitigate", "increase", "ignore", "start"]}'::jsonb, 'mitigate', 30, true, CURRENT_TIMESTAMP),
('B2', 'VOCABULARY', 'MULTIPLE_CHOICE', '{"question": "It is ___ to wear a helmet when riding a motorcycle.", "options": ["optional", "mandatory", "suggested", "rare"]}'::jsonb, 'mandatory', 30, true, CURRENT_TIMESTAMP),
('B2', 'VOCABULARY', 'MULTIPLE_CHOICE', '{"question": "He was ___ for his outstanding contribution to science.", "options": ["punished", "ignored", "acclaimed", "forgotten"]}'::jsonb, 'acclaimed', 30, true, CURRENT_TIMESTAMP),
('B2', 'GRAMMAR', 'MULTIPLE_CHOICE', '{"question": "If I had known you were coming, I ___ a cake.", "options": ["will bake", "would bake", "would have baked", "baked"]}'::jsonb, 'would have baked', 30, true, CURRENT_TIMESTAMP),
('B2', 'GRAMMAR', 'MULTIPLE_CHOICE', '{"question": "By next year, I ___ from university.", "options": ["will graduate", "graduate", "will have graduated", "graduated"]}'::jsonb, 'will have graduated', 30, true, CURRENT_TIMESTAMP),
('B2', 'GRAMMAR', 'MULTIPLE_CHOICE', '{"question": "Not only ___ late, but he also forgot his passport.", "options": ["was he", "he was", "is he", "he is"]}'::jsonb, 'was he', 30, true, CURRENT_TIMESTAMP),
('B2', 'GRAMMAR', 'FILL_BLANK', '{"question": "He is accustomed ___ waking up early."}'::jsonb, 'to', 30, true, CURRENT_TIMESTAMP),
('B2', 'GRAMMAR', 'FILL_BLANK', '{"question": "Despite ___ tired, she finished the marathon."}'::jsonb, 'being', 30, true, CURRENT_TIMESTAMP),
('B2', 'READING', 'READING_COMPREHENSION', '{"text": "The novel explores themes of isolation and redemption in a dystopian society where emotions are suppressed.", "question": "What is one theme of the novel?", "options": ["Technology", "Redemption", "Romance", "Adventure"]}'::jsonb, 'Redemption', 90, true, CURRENT_TIMESTAMP),
('B2', 'READING', 'READING_COMPREHENSION', '{"text": "Solar energy is becoming increasingly viable as technological advancements drive down costs.", "question": "Why is solar energy becoming more viable?", "options": ["It is fashionable", "Costs are going down", "It is getting hotter", "People like the sun"]}'::jsonb, 'Costs are going down', 90, true, CURRENT_TIMESTAMP),
('B2', 'READING', 'READING_COMPREHENSION', '{"text": "The company faced severe backlash after the CEO''s controversial remarks on social media.", "question": "What caused the backlash?", "options": ["A bad product", "The CEO''s remarks", "High prices", "Poor customer service"]}'::jsonb, 'The CEO''s remarks', 90, true, CURRENT_TIMESTAMP),
('B2', 'READING', 'READING_COMPREHENSION', '{"text": "While many praise the new policy, critics argue it will stifle innovation in the long run.", "question": "What do critics think of the policy?", "options": ["It is perfect", "It will stifle innovation", "It is too expensive", "It will help everyone"]}'::jsonb, 'It will stifle innovation', 90, true, CURRENT_TIMESTAMP),
('B2', 'READING', 'READING_COMPREHENSION', '{"text": "Regular exercise is paramount for maintaining both physical and mental well-being.", "question": "What does ''paramount'' mean here?", "options": ["Optional", "Extremely important", "Dangerous", "Useless"]}'::jsonb, 'Extremely important', 90, true, CURRENT_TIMESTAMP),
('B2', 'PRONUNCIATION', 'PRONUNCIATION', '{"word": "hierarchy", "ipa": "/ˈhaɪərɑːrki/"}'::jsonb, 'hierarchy', 10, true, CURRENT_TIMESTAMP),
('B2', 'PRONUNCIATION', 'PRONUNCIATION', '{"word": "subtle", "ipa": "/ˈsʌtl/"}'::jsonb, 'subtle', 10, true, CURRENT_TIMESTAMP),
('B2', 'PRONUNCIATION', 'PRONUNCIATION', '{"word": "entrepreneur", "ipa": "/ˌɑːntrəprəˈnɜːr/"}'::jsonb, 'entrepreneur', 10, true, CURRENT_TIMESTAMP),
('B2', 'PRONUNCIATION', 'PRONUNCIATION', '{"word": "chaos", "ipa": "/ˈkeɪɑːs/"}'::jsonb, 'chaos', 10, true, CURRENT_TIMESTAMP),
('B2', 'PRONUNCIATION', 'PRONUNCIATION', '{"word": "colleague", "ipa": "/ˈkɑːliːɡ/"}'::jsonb, 'colleague', 10, true, CURRENT_TIMESTAMP),

-- C1 (20 questions)
('C1', 'VOCABULARY', 'MULTIPLE_CHOICE', '{"question": "His speech was full of ___ promises that he had no intention of keeping.", "options": ["vacuous", "sincere", "profound", "genuine"]}'::jsonb, 'vacuous', 30, true, CURRENT_TIMESTAMP),
('C1', 'VOCABULARY', 'MULTIPLE_CHOICE', '{"question": "The evidence presented was completely ___, leaving no room for doubt.", "options": ["ambiguous", "irrefutable", "questionable", "vague"]}'::jsonb, 'irrefutable', 30, true, CURRENT_TIMESTAMP),
('C1', 'VOCABULARY', 'MULTIPLE_CHOICE', '{"question": "The artist''s work is characterized by a ___ blend of classical and modern styles.", "options": ["discordant", "seamless", "clumsy", "jarring"]}'::jsonb, 'seamless', 30, true, CURRENT_TIMESTAMP),
('C1', 'VOCABULARY', 'MULTIPLE_CHOICE', '{"question": "She has a ___ for remembering names and faces.", "options": ["knack", "struggle", "deficit", "void"]}'::jsonb, 'knack', 30, true, CURRENT_TIMESTAMP),
('C1', 'VOCABULARY', 'MULTIPLE_CHOICE', '{"question": "The negotiations reached an ___ due to uncompromising stances from both sides.", "options": ["agreement", "impasse", "outcome", "alliance"]}'::jsonb, 'impasse', 30, true, CURRENT_TIMESTAMP),
('C1', 'GRAMMAR', 'MULTIPLE_CHOICE', '{"question": "It is imperative that she ___ present at the meeting.", "options": ["is", "was", "be", "has been"]}'::jsonb, 'be', 30, true, CURRENT_TIMESTAMP),
('C1', 'GRAMMAR', 'MULTIPLE_CHOICE', '{"question": "___ you to change your mind, please inform us immediately.", "options": ["If", "Should", "Were", "Had"]}'::jsonb, 'Were', 30, true, CURRENT_TIMESTAMP),
('C1', 'GRAMMAR', 'MULTIPLE_CHOICE', '{"question": "Scarcely ___ the house when it started pouring.", "options": ["did I leave", "I left", "had I left", "have I left"]}'::jsonb, 'had I left', 30, true, CURRENT_TIMESTAMP),
('C1', 'GRAMMAR', 'FILL_BLANK', '{"question": "___ had we started eating when the fire alarm rang."}'::jsonb, 'Hardly', 30, true, CURRENT_TIMESTAMP),
('C1', 'GRAMMAR', 'FILL_BLANK', '{"question": "No sooner had she spoken ___ she realized her mistake."}'::jsonb, 'than', 30, true, CURRENT_TIMESTAMP),
('C1', 'READING', 'READING_COMPREHENSION', '{"text": "The proliferation of digital media has inexorably altered the landscape of modern journalism, rendering traditional print media increasingly obsolete.", "question": "What is happening to traditional print media?", "options": ["It is becoming more popular", "It is becoming obsolete", "It is merging with digital media", "It is unaffected"]}'::jsonb, 'It is becoming obsolete', 90, true, CURRENT_TIMESTAMP),
('C1', 'READING', 'READING_COMPREHENSION', '{"text": "The ubiquitous nature of smartphones has engendered a paradigm shift in interpersonal communication, often at the expense of face-to-face interaction.", "question": "What is negatively affected by smartphones according to the text?", "options": ["Global economies", "Face-to-face interaction", "Internet speeds", "Digital marketing"]}'::jsonb, 'Face-to-face interaction', 90, true, CURRENT_TIMESTAMP),
('C1', 'READING', 'READING_COMPREHENSION', '{"text": "Despite his ostensible reluctance to lead the project, his meticulous planning belied a deep-seated ambition.", "question": "What was true about his real feelings towards the project?", "options": ["He hated it", "He was ambitious about it", "He was completely indifferent", "He wanted someone else to do it"]}'::jsonb, 'He was ambitious about it', 90, true, CURRENT_TIMESTAMP),
('C1', 'READING', 'READING_COMPREHENSION', '{"text": "The esoteric terminology used in the paper alienated a significant portion of its intended audience.", "question": "Why did the audience feel alienated?", "options": ["The paper was too long", "The language was highly specialized", "The topic was boring", "The author was rude"]}'::jsonb, 'The language was highly specialized', 90, true, CURRENT_TIMESTAMP),
('C1', 'READING', 'READING_COMPREHENSION', '{"text": "Mitigating the deleterious effects of climate change requires an unprecedented level of international cooperation.", "question": "What does ''deleterious'' mean?", "options": ["Harmful", "Beneficial", "Minor", "Invisible"]}'::jsonb, 'Harmful', 90, true, CURRENT_TIMESTAMP),
('C1', 'PRONUNCIATION', 'PRONUNCIATION', '{"word": "epitome", "ipa": "/ɪˈpɪtəmi/"}'::jsonb, 'epitome', 10, true, CURRENT_TIMESTAMP),
('C1', 'PRONUNCIATION', 'PRONUNCIATION', '{"word": "anemone", "ipa": "/əˈneməni/"}'::jsonb, 'anemone', 10, true, CURRENT_TIMESTAMP),
('C1', 'PRONUNCIATION', 'PRONUNCIATION', '{"word": "synecdoche", "ipa": "/sɪˈnekdəki/"}'::jsonb, 'synecdoche', 10, true, CURRENT_TIMESTAMP),
('C1', 'PRONUNCIATION', 'PRONUNCIATION', '{"word": "cacophony", "ipa": "/kəˈkɑːfəni/"}'::jsonb, 'cacophony', 10, true, CURRENT_TIMESTAMP),
('C1', 'PRONUNCIATION', 'PRONUNCIATION', '{"word": "ubiquitous", "ipa": "/juːˈbɪkwɪtəs/"}'::jsonb, 'ubiquitous', 10, true, CURRENT_TIMESTAMP);
