--
-- PostgreSQL database dump
--

-- \restrict EXQKXQfpYJt5HZcsgmeWgImgWGIk5Dxfx0w7dfnSVkXbzPSDo7IqWeLkYRttqo5

-- Dumped from database version 15.18
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
-- SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: assignment_submissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.assignment_submissions (
    id bigint NOT NULL,
    commented_at timestamp(6) without time zone,
    result_ref_id bigint,
    submitted_at timestamp(6) without time zone,
    teacher_audio_comment_url character varying(500),
    teacher_comment_text text,
    assignment_id bigint NOT NULL,
    student_id bigint NOT NULL
);


ALTER TABLE public.assignment_submissions OWNER TO postgres;

--
-- Name: assignment_submissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.assignment_submissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assignment_submissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assignments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.assignments (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    deadline_at timestamp(6) without time zone,
    module_type character varying(255) NOT NULL,
    ref_id bigint NOT NULL,
    title character varying(300) NOT NULL,
    class_id bigint NOT NULL,
    teacher_id bigint NOT NULL,
    CONSTRAINT assignments_module_type_check CHECK (((module_type)::text = ANY ((ARRAY['PRONUNCIATION'::character varying, 'VOCABULARY'::character varying, 'SPEAKING'::character varying])::text[])))
);


ALTER TABLE public.assignments OWNER TO postgres;

--
-- Name: assignments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.assignments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assignments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: class_students; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.class_students (
    joined_at timestamp(6) without time zone NOT NULL,
    status character varying(255) NOT NULL,
    class_id bigint NOT NULL,
    student_id bigint NOT NULL,
    CONSTRAINT class_students_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))
);


ALTER TABLE public.class_students OWNER TO postgres;

--
-- Name: classes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.classes (
    id bigint NOT NULL,
    cefr_target character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    description text,
    is_active boolean NOT NULL,
    name character varying(200) NOT NULL,
    teacher_id bigint NOT NULL,
    CONSTRAINT classes_cefr_target_check CHECK (((cefr_target)::text = ANY ((ARRAY['A1'::character varying, 'A2'::character varying, 'B1'::character varying, 'B2'::character varying, 'C1'::character varying])::text[])))
);


ALTER TABLE public.classes OWNER TO postgres;

--
-- Name: classes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.classes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.classes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: daily_goals; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.daily_goals (
    id bigint NOT NULL,
    earned_xp smallint NOT NULL,
    goal_date date NOT NULL,
    is_completed boolean NOT NULL,
    target_xp smallint NOT NULL,
    student_id bigint NOT NULL
);


ALTER TABLE public.daily_goals OWNER TO postgres;

--
-- Name: daily_goals_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.daily_goals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.daily_goals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ipa_example_words; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ipa_example_words (
    id bigint NOT NULL,
    audio_url character varying(500) NOT NULL,
    ipa_transcription character varying(200) NOT NULL,
    word character varying(100) NOT NULL,
    phoneme_id smallint NOT NULL
);


ALTER TABLE public.ipa_example_words OWNER TO postgres;

--
-- Name: ipa_example_words_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ipa_example_words ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ipa_example_words_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ipa_phonemes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ipa_phonemes (
    id smallint NOT NULL,
    audio_female_url character varying(500) NOT NULL,
    audio_male_url character varying(500) NOT NULL,
    cefr_intro_level character varying(255) NOT NULL,
    is_common_vn_error boolean NOT NULL,
    name_vi character varying(100) NOT NULL,
    phoneme_type character varying(255) NOT NULL,
    symbol character varying(10) NOT NULL,
    video_mouth_url character varying(500),
    CONSTRAINT ipa_phonemes_cefr_intro_level_check CHECK (((cefr_intro_level)::text = ANY ((ARRAY['A1'::character varying, 'A2'::character varying, 'B1'::character varying, 'B2'::character varying, 'C1'::character varying])::text[]))),
    CONSTRAINT ipa_phonemes_phoneme_type_check CHECK (((phoneme_type)::text = ANY ((ARRAY['VOWEL_MONO'::character varying, 'VOWEL_DIPH'::character varying, 'CONSONANT'::character varying, 'SPECIAL'::character varying])::text[])))
);


ALTER TABLE public.ipa_phonemes OWNER TO postgres;

--
-- Name: ipa_phonemes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ipa_phonemes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ipa_phonemes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: minigame_results; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.minigame_results (
    id bigint NOT NULL,
    duration_seconds smallint,
    game_type character varying(255) NOT NULL,
    played_at timestamp(6) without time zone NOT NULL,
    score smallint NOT NULL,
    xp_earned smallint NOT NULL,
    student_id bigint NOT NULL,
    topic_id smallint,
    CONSTRAINT minigame_results_game_type_check CHECK (((game_type)::text = ANY ((ARRAY['LISTEN_CHOOSE'::character varying, 'WORD_SCRAMBLE'::character varying, 'FILL_CONTEXT'::character varying, 'MATCHING_FLASH'::character varying])::text[])))
);


ALTER TABLE public.minigame_results OWNER TO postgres;

--
-- Name: minigame_results_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.minigame_results ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.minigame_results_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    body text,
    created_at timestamp(6) without time zone NOT NULL,
    is_read boolean NOT NULL,
    ref_url character varying(500),
    title character varying(300) NOT NULL,
    type character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY['STREAK_REMINDER'::character varying, 'ASSIGNMENT_DUE'::character varying, 'NEW_MATERIAL'::character varying, 'TEACHER_COMMENT'::character varying, 'SYSTEM'::character varying])::text[])))
);


ALTER TABLE public.notifications OWNER TO postgres;

--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: placement_test_answers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.placement_test_answers (
    id bigint NOT NULL,
    answer_given character varying(500),
    answered_at timestamp(6) without time zone NOT NULL,
    is_correct boolean,
    time_spent_ms integer,
    question_id bigint NOT NULL,
    session_id bigint NOT NULL
);


ALTER TABLE public.placement_test_answers OWNER TO postgres;

--
-- Name: placement_test_answers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.placement_test_answers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.placement_test_answers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: placement_test_sessions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.placement_test_sessions (
    id bigint NOT NULL,
    confidence_score numeric(5,2),
    current_cefr_estimate character varying(255),
    current_question_index integer NOT NULL,
    is_completed boolean NOT NULL,
    last_activity_at timestamp(6) without time zone NOT NULL,
    started_at timestamp(6) without time zone NOT NULL,
    student_id bigint NOT NULL,
    CONSTRAINT placement_test_sessions_current_cefr_estimate_check CHECK (((current_cefr_estimate)::text = ANY ((ARRAY['A1'::character varying, 'A2'::character varying, 'B1'::character varying, 'B2'::character varying, 'C1'::character varying])::text[])))
);


ALTER TABLE public.placement_test_sessions OWNER TO postgres;

--
-- Name: placement_test_sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.placement_test_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.placement_test_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pronunciation_practice_logs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pronunciation_practice_logs (
    id bigint NOT NULL,
    audio_url character varying(500),
    completeness_score smallint,
    fluency_score smallint,
    overall_score smallint NOT NULL,
    phoneme_detail_json jsonb,
    practice_type character varying(255) NOT NULL,
    practiced_at timestamp(6) without time zone NOT NULL,
    ref_id bigint NOT NULL,
    stress_correct boolean,
    student_id bigint NOT NULL,
    CONSTRAINT pronunciation_practice_logs_practice_type_check CHECK (((practice_type)::text = ANY ((ARRAY['PHONEME'::character varying, 'WORD'::character varying, 'SENTENCE'::character varying])::text[])))
);


ALTER TABLE public.pronunciation_practice_logs OWNER TO postgres;

--
-- Name: pronunciation_practice_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pronunciation_practice_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pronunciation_practice_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: questions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.questions (
    id bigint NOT NULL,
    cefr_level character varying(255) NOT NULL,
    content_json jsonb NOT NULL,
    correct_answer character varying(500) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    difficulty_index numeric(4,3),
    is_active boolean NOT NULL,
    question_type character varying(255) NOT NULL,
    skill character varying(255) NOT NULL,
    timeout_seconds integer NOT NULL,
    CONSTRAINT questions_cefr_level_check CHECK (((cefr_level)::text = ANY ((ARRAY['A1'::character varying, 'A2'::character varying, 'B1'::character varying, 'B2'::character varying, 'C1'::character varying])::text[]))),
    CONSTRAINT questions_question_type_check CHECK (((question_type)::text = ANY ((ARRAY['MULTIPLE_CHOICE'::character varying, 'FILL_BLANK'::character varying, 'READING_COMPREHENSION'::character varying, 'LISTENING'::character varying, 'PRONUNCIATION'::character varying])::text[]))),
    CONSTRAINT questions_skill_check CHECK (((skill)::text = ANY ((ARRAY['VOCABULARY'::character varying, 'GRAMMAR'::character varying, 'READING'::character varying, 'LISTENING'::character varying, 'PRONUNCIATION'::character varying])::text[])))
);


ALTER TABLE public.questions OWNER TO postgres;

--
-- Name: questions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.questions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.questions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: speaking_scenarios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.speaking_scenarios (
    id smallint NOT NULL,
    ai_role_avatar_url character varying(500),
    ai_role_name character varying(100) NOT NULL,
    ai_system_prompt text NOT NULL,
    cefr_level character varying(255) NOT NULL,
    context_description text NOT NULL,
    goal_description text NOT NULL,
    hint_phrases_json jsonb,
    is_active boolean NOT NULL,
    title_en character varying(200) NOT NULL,
    title_vi character varying(200) NOT NULL,
    topic_id smallint,
    CONSTRAINT speaking_scenarios_cefr_level_check CHECK (((cefr_level)::text = ANY ((ARRAY['A1'::character varying, 'A2'::character varying, 'B1'::character varying, 'B2'::character varying, 'C1'::character varying])::text[])))
);


ALTER TABLE public.speaking_scenarios OWNER TO postgres;

--
-- Name: speaking_scenarios_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.speaking_scenarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.speaking_scenarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: speaking_sessions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.speaking_sessions (
    id bigint NOT NULL,
    ended_at timestamp(6) without time zone,
    evaluation_json jsonb,
    fluency_score smallint,
    hint_used_count smallint NOT NULL,
    intonation_score smallint,
    started_at timestamp(6) without time zone NOT NULL,
    task_completion_score smallint,
    xp_earned smallint,
    scenario_id smallint NOT NULL,
    student_id bigint NOT NULL
);


ALTER TABLE public.speaking_sessions OWNER TO postgres;

--
-- Name: speaking_sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.speaking_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.speaking_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: speaking_turns; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.speaking_turns (
    id bigint NOT NULL,
    audio_url character varying(500),
    created_at timestamp(6) without time zone NOT NULL,
    grammar_errors_json jsonb,
    speaker character varying(255) NOT NULL,
    transcript_text text NOT NULL,
    turn_index smallint NOT NULL,
    vocabulary_suggestions_json jsonb,
    session_id bigint NOT NULL,
    CONSTRAINT speaking_turns_speaker_check CHECK (((speaker)::text = ANY ((ARRAY['STUDENT'::character varying, 'AI'::character varying])::text[])))
);


ALTER TABLE public.speaking_turns OWNER TO postgres;

--
-- Name: speaking_turns_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.speaking_turns ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.speaking_turns_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: student_onboarding; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.student_onboarding (
    id bigint NOT NULL,
    daily_goal_xp smallint NOT NULL,
    goal_survey_json jsonb,
    onboarding_completed boolean NOT NULL,
    onboarding_completed_at timestamp(6) without time zone,
    placement_cefr_level character varying(255),
    placement_completed_at timestamp(6) without time zone,
    placement_grammar_score smallint,
    placement_listening_score smallint,
    placement_pronunciation_score smallint,
    placement_reading_score smallint,
    placement_vocab_score smallint,
    reminder_time time(6) without time zone,
    roadmap_json jsonb,
    student_id bigint NOT NULL,
    CONSTRAINT student_onboarding_placement_cefr_level_check CHECK (((placement_cefr_level)::text = ANY ((ARRAY['A1'::character varying, 'A2'::character varying, 'B1'::character varying, 'B2'::character varying, 'C1'::character varying])::text[])))
);


ALTER TABLE public.student_onboarding OWNER TO postgres;

--
-- Name: student_onboarding_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.student_onboarding ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_onboarding_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: student_phoneme_bookmarks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.student_phoneme_bookmarks (
    bookmarked_at timestamp(6) without time zone NOT NULL,
    phoneme_id smallint NOT NULL,
    student_id bigint NOT NULL
);


ALTER TABLE public.student_phoneme_bookmarks OWNER TO postgres;

--
-- Name: student_stats; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.student_stats (
    student_id bigint NOT NULL,
    current_streak smallint NOT NULL,
    last_activity_date date,
    longest_streak smallint NOT NULL,
    streak_freeze_count smallint NOT NULL,
    total_study_minutes integer NOT NULL,
    total_xp integer NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);


ALTER TABLE public.student_stats OWNER TO postgres;

--
-- Name: student_vocabulary_progress; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.student_vocabulary_progress (
    id bigint NOT NULL,
    correct_count smallint NOT NULL,
    incorrect_count smallint NOT NULL,
    last_practiced_at timestamp(6) without time zone,
    next_review_at timestamp(6) without time zone,
    status character varying(255) NOT NULL,
    student_id bigint NOT NULL,
    vocabulary_id bigint NOT NULL,
    CONSTRAINT student_vocabulary_progress_status_check CHECK (((status)::text = ANY ((ARRAY['NEW'::character varying, 'LEARNING'::character varying, 'REVIEWING'::character varying, 'MASTERED'::character varying])::text[])))
);


ALTER TABLE public.student_vocabulary_progress OWNER TO postgres;

--
-- Name: student_vocabulary_progress_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.student_vocabulary_progress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_vocabulary_progress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: syllabus_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.syllabus_items (
    id bigint NOT NULL,
    description text,
    scheduled_date date,
    sort_order smallint NOT NULL,
    title character varying(300) NOT NULL,
    week_number smallint NOT NULL,
    class_id bigint NOT NULL,
    material_id bigint
);


ALTER TABLE public.syllabus_items OWNER TO postgres;

--
-- Name: syllabus_items_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.syllabus_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.syllabus_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: teaching_materials; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.teaching_materials (
    id bigint NOT NULL,
    file_size_kb integer,
    file_type character varying(255) NOT NULL,
    file_url character varying(500) NOT NULL,
    is_live_presenting boolean NOT NULL,
    title character varying(300) NOT NULL,
    uploaded_at timestamp(6) without time zone NOT NULL,
    class_id bigint,
    teacher_id bigint NOT NULL,
    CONSTRAINT teaching_materials_file_type_check CHECK (((file_type)::text = ANY ((ARRAY['PDF'::character varying, 'DOCX'::character varying, 'PPTX'::character varying, 'MP4'::character varying, 'MP3'::character varying, 'OTHER'::character varying])::text[])))
);


ALTER TABLE public.teaching_materials OWNER TO postgres;

--
-- Name: teaching_materials_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.teaching_materials ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teaching_materials_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: topics; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.topics (
    id smallint NOT NULL,
    icon_url character varying(500),
    is_active boolean NOT NULL,
    name_en character varying(100) NOT NULL,
    name_vi character varying(100) NOT NULL
);


ALTER TABLE public.topics OWNER TO postgres;

--
-- Name: topics_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.topics ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.topics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    avatar_url character varying(1000),
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    full_name character varying(150) NOT NULL,
    is_active boolean NOT NULL,
    locale character varying(10) NOT NULL,
    password_hash character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    password character varying(255),
    phone character varying(15),
    provider character varying(500) NOT NULL,
    provider_id character varying(255),
    CONSTRAINT users_provider_check CHECK (((provider)::text = ANY ((ARRAY['LOCAL'::character varying, 'GOOGLE'::character varying])::text[]))),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['STUDENT'::character varying, 'TEACHER'::character varying, 'ADMIN'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vocabulary; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.vocabulary (
    id bigint NOT NULL,
    audio_uk_url character varying(500),
    audio_us_url character varying(500) NOT NULL,
    cefr_level character varying(255) NOT NULL,
    collocation_json jsonb,
    created_at timestamp(6) without time zone NOT NULL,
    definition_vi text NOT NULL,
    dialogue_json jsonb,
    example_sentences_json jsonb NOT NULL,
    image_url character varying(500),
    ipa_transcription character varying(300) NOT NULL,
    nuance_note text,
    published_at timestamp(6) without time zone,
    status character varying(255) NOT NULL,
    word character varying(150) NOT NULL,
    created_by bigint,
    topic_id smallint NOT NULL,
    CONSTRAINT vocabulary_cefr_level_check CHECK (((cefr_level)::text = ANY ((ARRAY['A1'::character varying, 'A2'::character varying, 'B1'::character varying, 'B2'::character varying, 'C1'::character varying])::text[]))),
    CONSTRAINT vocabulary_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'PENDING_REVIEW'::character varying, 'PUBLISHED'::character varying])::text[])))
);


ALTER TABLE public.vocabulary OWNER TO postgres;

--
-- Name: vocabulary_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.vocabulary ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vocabulary_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: xp_transactions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.xp_transactions (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    note character varying(255),
    source_ref_id bigint,
    source_type character varying(255) NOT NULL,
    xp_amount smallint NOT NULL,
    student_id bigint NOT NULL,
    CONSTRAINT xp_transactions_source_type_check CHECK (((source_type)::text = ANY ((ARRAY['PRONUNCIATION'::character varying, 'VOCABULARY'::character varying, 'MINIGAME'::character varying, 'SPEAKING'::character varying, 'STREAK_BONUS'::character varying, 'ONBOARDING'::character varying])::text[])))
);


ALTER TABLE public.xp_transactions OWNER TO postgres;

--
-- Name: xp_transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.xp_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.xp_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assignment_submissions assignment_submissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assignment_submissions
    ADD CONSTRAINT assignment_submissions_pkey PRIMARY KEY (id);


--
-- Name: assignments assignments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assignments
    ADD CONSTRAINT assignments_pkey PRIMARY KEY (id);


--
-- Name: class_students class_students_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.class_students
    ADD CONSTRAINT class_students_pkey PRIMARY KEY (class_id, student_id);


--
-- Name: classes classes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.classes
    ADD CONSTRAINT classes_pkey PRIMARY KEY (id);


--
-- Name: daily_goals daily_goals_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.daily_goals
    ADD CONSTRAINT daily_goals_pkey PRIMARY KEY (id);


--
-- Name: ipa_example_words ipa_example_words_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ipa_example_words
    ADD CONSTRAINT ipa_example_words_pkey PRIMARY KEY (id);


--
-- Name: ipa_phonemes ipa_phonemes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ipa_phonemes
    ADD CONSTRAINT ipa_phonemes_pkey PRIMARY KEY (id);


--
-- Name: minigame_results minigame_results_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.minigame_results
    ADD CONSTRAINT minigame_results_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: placement_test_answers placement_test_answers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.placement_test_answers
    ADD CONSTRAINT placement_test_answers_pkey PRIMARY KEY (id);


--
-- Name: placement_test_sessions placement_test_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.placement_test_sessions
    ADD CONSTRAINT placement_test_sessions_pkey PRIMARY KEY (id);


--
-- Name: pronunciation_practice_logs pronunciation_practice_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pronunciation_practice_logs
    ADD CONSTRAINT pronunciation_practice_logs_pkey PRIMARY KEY (id);


--
-- Name: questions questions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT questions_pkey PRIMARY KEY (id);


--
-- Name: speaking_scenarios speaking_scenarios_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.speaking_scenarios
    ADD CONSTRAINT speaking_scenarios_pkey PRIMARY KEY (id);


--
-- Name: speaking_sessions speaking_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.speaking_sessions
    ADD CONSTRAINT speaking_sessions_pkey PRIMARY KEY (id);


--
-- Name: speaking_turns speaking_turns_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.speaking_turns
    ADD CONSTRAINT speaking_turns_pkey PRIMARY KEY (id);


--
-- Name: student_onboarding student_onboarding_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_onboarding
    ADD CONSTRAINT student_onboarding_pkey PRIMARY KEY (id);


--
-- Name: student_phoneme_bookmarks student_phoneme_bookmarks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_phoneme_bookmarks
    ADD CONSTRAINT student_phoneme_bookmarks_pkey PRIMARY KEY (phoneme_id, student_id);


--
-- Name: student_stats student_stats_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_stats
    ADD CONSTRAINT student_stats_pkey PRIMARY KEY (student_id);


--
-- Name: student_vocabulary_progress student_vocabulary_progress_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_vocabulary_progress
    ADD CONSTRAINT student_vocabulary_progress_pkey PRIMARY KEY (id);


--
-- Name: syllabus_items syllabus_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.syllabus_items
    ADD CONSTRAINT syllabus_items_pkey PRIMARY KEY (id);


--
-- Name: teaching_materials teaching_materials_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teaching_materials
    ADD CONSTRAINT teaching_materials_pkey PRIMARY KEY (id);


--
-- Name: topics topics_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.topics
    ADD CONSTRAINT topics_pkey PRIMARY KEY (id);


--
-- Name: student_vocabulary_progress uk1aox4dv4tl427x4ifteh6t1ei; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_vocabulary_progress
    ADD CONSTRAINT uk1aox4dv4tl427x4ifteh6t1ei UNIQUE (student_id, vocabulary_id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: student_onboarding ukar0tu0q2b7y2w7es0yd279m7a; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_onboarding
    ADD CONSTRAINT ukar0tu0q2b7y2w7es0yd279m7a UNIQUE (student_id);


--
-- Name: ipa_phonemes ukcxse2xrhatnoyhn5837owmr7m; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ipa_phonemes
    ADD CONSTRAINT ukcxse2xrhatnoyhn5837owmr7m UNIQUE (symbol);


--
-- Name: assignment_submissions ukjpaoiqlq2bm3rv52lcri47g4s; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assignment_submissions
    ADD CONSTRAINT ukjpaoiqlq2bm3rv52lcri47g4s UNIQUE (assignment_id, student_id);


--
-- Name: daily_goals ukt836mxdixf9levt51v3r4w5g1; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.daily_goals
    ADD CONSTRAINT ukt836mxdixf9levt51v3r4w5g1 UNIQUE (student_id, goal_date);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: vocabulary vocabulary_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vocabulary
    ADD CONSTRAINT vocabulary_pkey PRIMARY KEY (id);


--
-- Name: xp_transactions xp_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.xp_transactions
    ADD CONSTRAINT xp_transactions_pkey PRIMARY KEY (id);


--
-- Name: assignments fk15vvra255mh2h6merxffxmb2t; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assignments
    ADD CONSTRAINT fk15vvra255mh2h6merxffxmb2t FOREIGN KEY (class_id) REFERENCES public.classes(id);


--
-- Name: classes fk4tv5efpqhlo8xg8l8dpba8v75; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.classes
    ADD CONSTRAINT fk4tv5efpqhlo8xg8l8dpba8v75 FOREIGN KEY (teacher_id) REFERENCES public.users(id);


--
-- Name: daily_goals fk4uci1791837gu1jgtsyycbim4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.daily_goals
    ADD CONSTRAINT fk4uci1791837gu1jgtsyycbim4 FOREIGN KEY (student_id) REFERENCES public.users(id);


--
-- Name: teaching_materials fk4wr6ic02ryw95j50rth55ihr3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teaching_materials
    ADD CONSTRAINT fk4wr6ic02ryw95j50rth55ihr3 FOREIGN KEY (class_id) REFERENCES public.classes(id);


--
-- Name: assignments fk67msc7a52b0l2pttoq5bhm6bk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assignments
    ADD CONSTRAINT fk67msc7a52b0l2pttoq5bhm6bk FOREIGN KEY (teacher_id) REFERENCES public.users(id);


--
-- Name: syllabus_items fk83bm3ecbf92dhcnfcbhmx15x4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.syllabus_items
    ADD CONSTRAINT fk83bm3ecbf92dhcnfcbhmx15x4 FOREIGN KEY (class_id) REFERENCES public.classes(id);


--
-- Name: vocabulary fk9vygs7gejs8odmmsueffqgwag; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vocabulary
    ADD CONSTRAINT fk9vygs7gejs8odmmsueffqgwag FOREIGN KEY (topic_id) REFERENCES public.topics(id);


--
-- Name: student_phoneme_bookmarks fk9w9460ntrachrurxxvw8552nj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_phoneme_bookmarks
    ADD CONSTRAINT fk9w9460ntrachrurxxvw8552nj FOREIGN KEY (student_id) REFERENCES public.users(id);


--
-- Name: notifications fk9y21adhxn0ayjhfocscqox7bh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fk9y21adhxn0ayjhfocscqox7bh FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: speaking_sessions fkanxt32x61x0po2i0gce0tk6h9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.speaking_sessions
    ADD CONSTRAINT fkanxt32x61x0po2i0gce0tk6h9 FOREIGN KEY (student_id) REFERENCES public.users(id);


--
-- Name: ipa_example_words fkaw4w5cotrn28bgsh0nofbay8o; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ipa_example_words
    ADD CONSTRAINT fkaw4w5cotrn28bgsh0nofbay8o FOREIGN KEY (phoneme_id) REFERENCES public.ipa_phonemes(id);


--
-- Name: speaking_sessions fkbd3cgm8iuxn5unrn6xwthdln2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.speaking_sessions
    ADD CONSTRAINT fkbd3cgm8iuxn5unrn6xwthdln2 FOREIGN KEY (scenario_id) REFERENCES public.speaking_scenarios(id);


--
-- Name: xp_transactions fkchtjdtck6545340l8e59507hl; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.xp_transactions
    ADD CONSTRAINT fkchtjdtck6545340l8e59507hl FOREIGN KEY (student_id) REFERENCES public.users(id);


--
-- Name: placement_test_answers fke3n4ukow8svlevvesdr6r8ddn; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.placement_test_answers
    ADD CONSTRAINT fke3n4ukow8svlevvesdr6r8ddn FOREIGN KEY (session_id) REFERENCES public.placement_test_sessions(id);


--
-- Name: vocabulary fkebtdmns7gd0ey5hv54macdtyp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vocabulary
    ADD CONSTRAINT fkebtdmns7gd0ey5hv54macdtyp FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: assignment_submissions fkgf6lwnlqvnetehdftwcij7r5g; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assignment_submissions
    ADD CONSTRAINT fkgf6lwnlqvnetehdftwcij7r5g FOREIGN KEY (student_id) REFERENCES public.users(id);


--
-- Name: minigame_results fkhw0wxus2923mlpatj33rvvmq1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.minigame_results
    ADD CONSTRAINT fkhw0wxus2923mlpatj33rvvmq1 FOREIGN KEY (topic_id) REFERENCES public.topics(id);


--
-- Name: class_students fki67hsuppqm0qnfgn2x8d7v2lj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.class_students
    ADD CONSTRAINT fki67hsuppqm0qnfgn2x8d7v2lj FOREIGN KEY (student_id) REFERENCES public.users(id);


--
-- Name: placement_test_answers fkiy4ehtbtv5owqwwxfamnopty2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.placement_test_answers
    ADD CONSTRAINT fkiy4ehtbtv5owqwwxfamnopty2 FOREIGN KEY (question_id) REFERENCES public.questions(id);


--
-- Name: class_students fkjuh9br5vimkw71ko8qyswp3ci; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.class_students
    ADD CONSTRAINT fkjuh9br5vimkw71ko8qyswp3ci FOREIGN KEY (class_id) REFERENCES public.classes(id);


--
-- Name: speaking_turns fkkmb8lllx0x4sct24wkm1i2rpl; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.speaking_turns
    ADD CONSTRAINT fkkmb8lllx0x4sct24wkm1i2rpl FOREIGN KEY (session_id) REFERENCES public.speaking_sessions(id);


--
-- Name: pronunciation_practice_logs fkkmcww0x6jhy6w2sw2r1u6ccpe; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pronunciation_practice_logs
    ADD CONSTRAINT fkkmcww0x6jhy6w2sw2r1u6ccpe FOREIGN KEY (student_id) REFERENCES public.users(id);


--
-- Name: assignment_submissions fkm7i7ubgh7y2n6mvg8muw62oax; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assignment_submissions
    ADD CONSTRAINT fkm7i7ubgh7y2n6mvg8muw62oax FOREIGN KEY (assignment_id) REFERENCES public.assignments(id);


--
-- Name: minigame_results fkn80crkg0v85ruhq95b4wdua5l; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.minigame_results
    ADD CONSTRAINT fkn80crkg0v85ruhq95b4wdua5l FOREIGN KEY (student_id) REFERENCES public.users(id);


--
-- Name: student_vocabulary_progress fkncbk2ls3fccpvlkvo7e19bw4s; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_vocabulary_progress
    ADD CONSTRAINT fkncbk2ls3fccpvlkvo7e19bw4s FOREIGN KEY (student_id) REFERENCES public.users(id);


--
-- Name: student_onboarding fkoq62dqts85wnxhiw230ckvck6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_onboarding
    ADD CONSTRAINT fkoq62dqts85wnxhiw230ckvck6 FOREIGN KEY (student_id) REFERENCES public.users(id);


--
-- Name: speaking_scenarios fkoyoj581ja1aqgnydr7b7o0vte; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.speaking_scenarios
    ADD CONSTRAINT fkoyoj581ja1aqgnydr7b7o0vte FOREIGN KEY (topic_id) REFERENCES public.topics(id);


--
-- Name: student_stats fkp1s09cjchlficop9agry8drbl; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_stats
    ADD CONSTRAINT fkp1s09cjchlficop9agry8drbl FOREIGN KEY (student_id) REFERENCES public.users(id);


--
-- Name: syllabus_items fkpex9kwrln5kip2hm5eufb4uie; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.syllabus_items
    ADD CONSTRAINT fkpex9kwrln5kip2hm5eufb4uie FOREIGN KEY (material_id) REFERENCES public.teaching_materials(id);


--
-- Name: placement_test_sessions fkqhodhwq7wchunr7r1ieqjp7vv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.placement_test_sessions
    ADD CONSTRAINT fkqhodhwq7wchunr7r1ieqjp7vv FOREIGN KEY (student_id) REFERENCES public.users(id);


--
-- Name: student_vocabulary_progress fkr6g25tiy8koh8uknb2itvnlrj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_vocabulary_progress
    ADD CONSTRAINT fkr6g25tiy8koh8uknb2itvnlrj FOREIGN KEY (vocabulary_id) REFERENCES public.vocabulary(id);


--
-- Name: student_phoneme_bookmarks fks2l5wj52ponvuelid6i8ntthm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_phoneme_bookmarks
    ADD CONSTRAINT fks2l5wj52ponvuelid6i8ntthm FOREIGN KEY (phoneme_id) REFERENCES public.ipa_phonemes(id);


--
-- Name: teaching_materials fkt8qd2cnbsa8c9afdyaoyvmpcw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teaching_materials
    ADD CONSTRAINT fkt8qd2cnbsa8c9afdyaoyvmpcw FOREIGN KEY (teacher_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

-- \unrestrict EXQKXQfpYJt5HZcsgmeWgImgWGIk5Dxfx0w7dfnSVkXbzPSDo7IqWeLkYRttqo5

