-- Durable speaking sessions and turn processing. Existing completed reports are retained.
ALTER TABLE speaking_sessions ADD COLUMN status varchar(32) NOT NULL DEFAULT 'ONGOING';
UPDATE speaking_sessions SET status = 'COMPLETED' WHERE ended_at IS NOT NULL;
ALTER TABLE speaking_sessions ADD COLUMN scenario_snapshot_json jsonb;
ALTER TABLE speaking_sessions ADD COLUMN hint_requests_json jsonb NOT NULL DEFAULT '[]';
ALTER TABLE speaking_turns ALTER COLUMN turn_index TYPE integer;
ALTER TABLE speaking_turns ADD COLUMN request_key varchar(100);
ALTER TABLE speaking_turns ADD COLUMN input_hash varchar(64);
ALTER TABLE speaking_turns ADD COLUMN status varchar(32) NOT NULL DEFAULT 'COMPLETED';
ALTER TABLE speaking_turns ADD COLUMN audio_data bytea;
ALTER TABLE speaking_turns ADD COLUMN audio_content_type varchar(100);
ALTER TABLE speaking_turns ADD COLUMN audio_metrics_json jsonb;
ALTER TABLE speaking_turns ADD COLUMN evaluation_status varchar(32) NOT NULL DEFAULT 'PENDING';
ALTER TABLE speaking_turns ADD COLUMN error_code varchar(100);
CREATE UNIQUE INDEX speaking_turn_request_key ON speaking_turns(session_id, request_key) WHERE request_key IS NOT NULL;
CREATE INDEX speaking_turn_order ON speaking_turns(session_id, turn_index);
CREATE TABLE speaking_jobs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id bigint NOT NULL REFERENCES speaking_sessions(id),
    turn_id bigint REFERENCES speaking_turns(id),
    kind varchar(32) NOT NULL,
    status varchar(32) NOT NULL DEFAULT 'PENDING',
    attempts integer NOT NULL DEFAULT 0,
    available_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lease_token varchar(36),
    error_code varchar(100)
);
CREATE INDEX speaking_job_poll ON speaking_jobs(status, available_at);

-- Freeze the scenario for legacy sessions as well.
UPDATE speaking_sessions s SET scenario_snapshot_json=jsonb_build_object(
 'prompt',c.ai_system_prompt,'context',c.context_description,'persona',c.ai_role_name,
 'goal',c.goal_description,'cefr',c.cefr_level,'hints',c.hint_phrases_json)
 FROM speaking_scenarios c WHERE s.scenario_id=c.id;
UPDATE speaking_turns SET evaluation_status='COMPLETED' WHERE speaker='STUDENT';
UPDATE speaking_turns SET evaluation_status='NOT_APPLICABLE' WHERE speaker='AI';
