-- Keep every historical turn; normalize duplicate legacy ordinals before enforcing order.
WITH ordered AS (
    SELECT id, row_number() OVER (PARTITION BY session_id ORDER BY turn_index, id) AS ordinal
    FROM speaking_turns
)
UPDATE speaking_turns t SET turn_index=o.ordinal FROM ordered o WHERE t.id=o.id;
CREATE UNIQUE INDEX speaking_turn_unique_order ON speaking_turns(session_id, turn_index);
ALTER TABLE speaking_turns ADD COLUMN response_text_ready boolean NOT NULL DEFAULT false;
UPDATE speaking_turns SET response_text_ready=true, error_code=null WHERE error_code='TEXT_READY';

ALTER TABLE speaking_jobs
    ADD COLUMN created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN started_at timestamp,
    ADD COLUMN finished_at timestamp,
    ADD COLUMN lease_expires_at timestamp,
    ADD COLUMN max_attempts integer NOT NULL DEFAULT 3,
    ADD COLUMN error_message varchar(500);
UPDATE speaking_jobs SET lease_expires_at=available_at WHERE status='RUNNING';
-- Fail migration rather than silently discard duplicate jobs if legacy data needs repair.
CREATE UNIQUE INDEX speaking_job_per_turn ON speaking_jobs(turn_id, kind) WHERE turn_id IS NOT NULL;
CREATE UNIQUE INDEX speaking_job_per_session ON speaking_jobs(session_id, kind) WHERE turn_id IS NULL;
CREATE INDEX speaking_job_lease ON speaking_jobs(lease_expires_at) WHERE status='RUNNING';
UPDATE speaking_sessions SET status='EVALUATION_FAILED' WHERE status='FAILED';

CREATE TABLE speaking_job_attempts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id bigint NOT NULL REFERENCES speaking_jobs(id),
    attempt_no integer NOT NULL,
    status varchar(32) NOT NULL,
    lease_token varchar(36) NOT NULL,
    started_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at timestamp,
    error_code varchar(100),
    error_message varchar(500),
    retryable boolean,
    UNIQUE(job_id, attempt_no)
);
