-- A mini-game round groups the per-question answers a student gives for one topic.
-- VOCABULARY assignments are now submitted with a COMPLETED round id instead of a single answer.
CREATE TABLE minigame_rounds (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id       BIGINT      NOT NULL REFERENCES users (id),
    topic_id         SMALLINT    NOT NULL REFERENCES topics (id),
    game_type        VARCHAR(32) NOT NULL,
    status           VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS',
    total_questions  INTEGER     NOT NULL DEFAULT 0,
    correct_count    INTEGER     NOT NULL DEFAULT 0,
    score            SMALLINT,
    xp_earned        INTEGER     NOT NULL DEFAULT 0,
    duration_seconds INTEGER     NOT NULL DEFAULT 0,
    started_at       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at     TIMESTAMP,
    CONSTRAINT chk_minigame_rounds_status CHECK (status IN ('IN_PROGRESS', 'COMPLETED')),
    CONSTRAINT chk_minigame_rounds_game_type CHECK (game_type IN ('LISTEN_CHOOSE', 'WORD_SCRAMBLE', 'FILL_CONTEXT', 'MATCHING_FLASH')),
    CONSTRAINT chk_minigame_rounds_counts CHECK (correct_count >= 0 AND correct_count <= total_questions),
    CONSTRAINT chk_minigame_rounds_score CHECK (score IS NULL OR score BETWEEN 0 AND 100)
);

CREATE INDEX idx_minigame_rounds_student_topic ON minigame_rounds (student_id, topic_id);

ALTER TABLE minigame_results ADD COLUMN round_id BIGINT REFERENCES minigame_rounds (id);
CREATE INDEX idx_minigame_results_round ON minigame_results (round_id);

-- Existing VOCABULARY submissions point at a single minigame_results row.
-- Wrap each of them in a one-question COMPLETED round so they keep working after the switch.
DO $$
DECLARE
    rec    RECORD;
    new_id BIGINT;
BEGIN
    FOR rec IN
        SELECT s.id AS submission_id, r.id AS result_id, r.student_id, r.topic_id, r.game_type,
               r.score, r.xp_earned, r.duration_seconds, r.played_at
        FROM assignment_submissions s
        JOIN assignments a ON a.id = s.assignment_id AND a.module_type = 'VOCABULARY'
        JOIN minigame_results r ON r.id = s.result_ref_id
        WHERE r.topic_id IS NOT NULL
    LOOP
        INSERT INTO minigame_rounds (student_id, topic_id, game_type, status, total_questions, correct_count,
                                     score, xp_earned, duration_seconds, started_at, completed_at)
        VALUES (rec.student_id, rec.topic_id, rec.game_type, 'COMPLETED', 1,
                CASE WHEN rec.score >= 100 THEN 1 ELSE 0 END,
                rec.score, rec.xp_earned, COALESCE(rec.duration_seconds, 0), rec.played_at, rec.played_at)
        RETURNING id INTO new_id;

        UPDATE minigame_results SET round_id = new_id WHERE id = rec.result_id;
        UPDATE assignment_submissions SET result_ref_id = new_id WHERE id = rec.submission_id;
    END LOOP;
END $$;
