CREATE TABLE public.roadmap_module_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    roadmap_version INTEGER NOT NULL,
    week_number INTEGER NOT NULL,
    module_index INTEGER NOT NULL,
    module_key VARCHAR(120) NOT NULL,
    module_type VARCHAR(40) NOT NULL,
    topic_id SMALLINT NULL REFERENCES public.topics(id) ON DELETE SET NULL,
    done_count INTEGER NOT NULL DEFAULT 0,
    total_count INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'NOT_STARTED',
    completed_at TIMESTAMP NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_roadmap_module_progress
        UNIQUE (student_id, roadmap_version, module_key),
    CONSTRAINT ck_roadmap_module_progress_version
        CHECK (roadmap_version >= 0),
    CONSTRAINT ck_roadmap_module_progress_position
        CHECK (week_number > 0 AND module_index >= 0),
    CONSTRAINT ck_roadmap_module_progress_counts
        CHECK (done_count >= 0 AND total_count >= 0 AND done_count <= total_count),
    CONSTRAINT ck_roadmap_module_progress_status
        CHECK (status IN ('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED'))
);

CREATE INDEX idx_roadmap_module_progress_student_version
    ON public.roadmap_module_progress (student_id, roadmap_version);

-- Supporting indexes for the three source-of-truth progress counts.
-- student_vocabulary_progress already has UNIQUE(student_id, vocabulary_id).
CREATE INDEX IF NOT EXISTS idx_speaking_sessions_roadmap_progress
    ON public.speaking_sessions (student_id, status, scenario_id);

CREATE INDEX IF NOT EXISTS idx_pronunciation_logs_roadmap_progress
    ON public.pronunciation_practice_logs (student_id, ref_id);

CREATE INDEX IF NOT EXISTS idx_ipa_example_words_phoneme
    ON public.ipa_example_words (phoneme_id, id);

CREATE INDEX IF NOT EXISTS idx_vocabulary_roadmap_snapshot
    ON public.vocabulary (topic_id, status, id);

CREATE INDEX IF NOT EXISTS idx_speaking_scenarios_roadmap_snapshot
    ON public.speaking_scenarios (topic_id, cefr_level, is_active, id);
