CREATE TABLE public.learner_profiles (
    student_id BIGINT PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
    cefr_level VARCHAR(2),
    cefr_source VARCHAR(20),
    cefr_assessed_at TIMESTAMP,
    overall_mastery NUMERIC(5,2),
    profile_version BIGINT NOT NULL DEFAULT 0,
    total_activities INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_learner_profile_cefr CHECK (
        cefr_level IS NULL OR cefr_level IN ('A1', 'A2', 'B1', 'B2', 'C1', 'C2')),
    CONSTRAINT ck_learner_profile_mastery CHECK (
        overall_mastery IS NULL OR overall_mastery BETWEEN 0 AND 100),
    CONSTRAINT ck_learner_profile_counts CHECK (
        profile_version >= 0 AND total_activities >= 0)
);

CREATE TABLE public.learner_skill_states (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    skill VARCHAR(20) NOT NULL,
    cefr_level VARCHAR(2),
    source VARCHAR(20) NOT NULL,
    mastery NUMERIC(5,2),
    recent_score NUMERIC(5,2),
    confidence NUMERIC(4,3) NOT NULL DEFAULT 0,
    evidence_weight NUMERIC(8,3) NOT NULL DEFAULT 0,
    evidence_count INTEGER NOT NULL DEFAULT 0,
    trend VARCHAR(10) NOT NULL DEFAULT 'STABLE',
    last_practiced_at TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_learner_skill_state UNIQUE (student_id, skill),
    CONSTRAINT ck_learner_skill_name CHECK (
        skill IN ('VOCABULARY', 'SPEAKING', 'PRONUNCIATION', 'READING', 'LISTENING', 'GRAMMAR')),
    CONSTRAINT ck_learner_skill_cefr CHECK (
        cefr_level IS NULL OR cefr_level IN ('A1', 'A2', 'B1', 'B2', 'C1', 'C2')),
    CONSTRAINT ck_learner_skill_source CHECK (source IN ('PLACEMENT', 'PRACTICE')),
    CONSTRAINT ck_learner_skill_scores CHECK (
        (mastery IS NULL OR mastery BETWEEN 0 AND 100)
        AND (recent_score IS NULL OR recent_score BETWEEN 0 AND 100)
        AND confidence BETWEEN 0 AND 1
        AND evidence_weight >= 0
        AND evidence_count >= 0),
    CONSTRAINT ck_learner_skill_trend CHECK (trend IN ('UP', 'DOWN', 'STABLE'))
);

CREATE INDEX idx_learner_skill_states_student
    ON public.learner_skill_states (student_id);
