CREATE TABLE public.student_daily_activity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    activity_date DATE NOT NULL,
    measured_seconds INTEGER NOT NULL DEFAULT 0,
    estimated_seconds INTEGER NOT NULL DEFAULT 0,
    activity_count INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_student_daily_activity UNIQUE (student_id, activity_date),
    CONSTRAINT ck_student_daily_activity_counts CHECK (
        measured_seconds >= 0 AND estimated_seconds >= 0 AND activity_count >= 0)
);

CREATE INDEX idx_student_daily_activity_student_date
    ON public.student_daily_activity (student_id, activity_date DESC);
