CREATE TABLE public.today_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    plan_date DATE NOT NULL,
    timezone VARCHAR(50) NOT NULL,
    revision INTEGER NOT NULL DEFAULT 1,
    profile_version BIGINT NOT NULL DEFAULT 0,
    rules_version VARCHAR(40) NOT NULL,
    budget_minutes INTEGER NOT NULL,
    estimated_minutes INTEGER NOT NULL DEFAULT 0,
    completed_minutes INTEGER NOT NULL DEFAULT 0,
    progress_percent NUMERIC(5,2) NOT NULL DEFAULT 0,
    input_hash VARCHAR(64) NOT NULL,
    dirty BOOLEAN NOT NULL DEFAULT FALSE,
    generated_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_today_plan_student_date UNIQUE (student_id, plan_date, timezone),
    CONSTRAINT ck_today_plan_revision CHECK (revision > 0 AND profile_version >= 0),
    CONSTRAINT ck_today_plan_budget CHECK (budget_minutes BETWEEN 5 AND 120),
    CONSTRAINT ck_today_plan_minutes CHECK (
        estimated_minutes >= 0 AND completed_minutes >= 0),
    CONSTRAINT ck_today_plan_progress CHECK (progress_percent BETWEEN 0 AND 100)
);

CREATE TABLE public.today_plan_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id BIGINT NOT NULL REFERENCES public.today_plans(id) ON DELETE CASCADE,
    recommendation_id VARCHAR(64) NOT NULL,
    type VARCHAR(40) NOT NULL,
    title VARCHAR(250),
    skill VARCHAR(20),
    target_json JSONB NOT NULL,
    navigation_json JSONB NOT NULL,
    reason_code VARCHAR(40) NOT NULL,
    reason_params JSONB NOT NULL DEFAULT '{}'::jsonb,
    priority VARCHAR(2),
    estimated_minutes INTEGER NOT NULL,
    completed_units INTEGER NOT NULL DEFAULT 0,
    total_units INTEGER NOT NULL DEFAULT 1,
    status VARCHAR(15) NOT NULL DEFAULT 'TODO',
    source_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    position INTEGER NOT NULL,
    last_included_revision INTEGER NOT NULL,
    completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_today_plan_recommendation UNIQUE (plan_id, recommendation_id),
    CONSTRAINT ck_today_plan_item_type CHECK (type IN (
        'VOCABULARY_REVIEW', 'ROADMAP_MODULE', 'PRONUNCIATION',
        'SPEAKING', 'ASSIGNMENT', 'VOCABULARY_TOPIC')),
    CONSTRAINT ck_today_plan_item_skill CHECK (
        skill IS NULL OR skill IN ('VOCABULARY', 'SPEAKING', 'PRONUNCIATION', 'READING', 'LISTENING', 'GRAMMAR')),
    CONSTRAINT ck_today_plan_item_priority CHECK (priority IS NULL OR priority IN ('P0', 'P1')),
    CONSTRAINT ck_today_plan_item_status CHECK (status IN ('TODO', 'IN_PROGRESS', 'COMPLETED', 'REMOVED')),
    CONSTRAINT ck_today_plan_item_units CHECK (
        estimated_minutes > 0 AND completed_units >= 0 AND total_units > 0
        AND completed_units <= total_units),
    CONSTRAINT ck_today_plan_item_position CHECK (position >= 0 AND last_included_revision > 0)
);

CREATE INDEX idx_today_plan_items_active
    ON public.today_plan_items (plan_id, status, position);
